import type { BetModeMeta } from 'state-shared';

/** Home Run bet modes — Double Chance + scatter buys. */
export const HOME_RUN_BET_MODE_META = {
	BASE: {
		mode: 'BASE',
		costMultiplier: 1.0,
		type: 'default',
		parent: '',
		children: '',
		assets: {
			icon: '',
			dialogImage: '',
			dialogVolatility: '',
			volatility: '',
			button: '',
		},
		text: {
			title: 'BASE',
			dialog: '',
			button: '',
			betAmountLabel: '',
			tickerIdle: 'PLACE YOUR BET',
			tickerSpin: 'GOOD LUCK',
			bannerText: '',
			description: '',
		},
		maxWin: 25000,
	},
	ANTE: {
		mode: 'ANTE',
		costMultiplier: 1.25,
		type: 'activate',
		parent: '',
		children: '',
		assets: {
			icon: '',
			dialogImage: '',
			dialogVolatility: '',
			volatility: '',
			button: '',
		},
		text: {
			title: 'DOUBLE CHANCE',
			dialog:
				'Double the chance to land FREE SPINS for 1.25× your bet. Stays active until you turn it off.',
			description: '≈2× chance to trigger FREE SPINS (1.25× bet).',
			button: 'ACTIVATE',
			betAmountLabel: 'DOUBLE CHANCE',
			tickerIdle: 'DOUBLE CHANCE ACTIVE',
			tickerSpin: 'GOOD LUCK',
			bannerText: '',
		},
		maxWin: 25000,
	},
	BONUS_3: {
		mode: 'BONUS_3',
		costMultiplier: 100,
		type: 'buy',
		parent: '',
		children: '',
		assets: {
			icon: '',
			dialogImage: '',
			dialogVolatility: '',
			volatility: '',
			button: '',
		},
		text: {
			title: 'BONUS 3',
			dialog: 'Buy FREE SPINS with 3 scatters (10 FS) for 100× your bet.',
			description: 'Force 3 SCATTER → 10 FREE SPINS (100× bet).',
			button: 'BUY',
			tickerIdle: 'PLACE YOUR BET',
			tickerSpin: 'BONUS 3 BUY',
			bannerText: '',
		},
		maxWin: 25000,
	},
	BONUS_4: {
		mode: 'BONUS_4',
		costMultiplier: 160,
		type: 'buy',
		parent: '',
		children: '',
		assets: {
			icon: '',
			dialogImage: '',
			dialogVolatility: '',
			volatility: '',
			button: '',
		},
		text: {
			title: 'BONUS 4',
			dialog: 'Buy FREE SPINS with 4 scatters (12 FS) for 160× your bet.',
			description: 'Force 4 SCATTER → 12 FREE SPINS (160× bet).',
			button: 'BUY',
			tickerIdle: 'PLACE YOUR BET',
			tickerSpin: 'BONUS 4 BUY',
			bannerText: '',
		},
		maxWin: 25000,
	},
	BONUS: {
		mode: 'BONUS',
		costMultiplier: 200,
		type: 'buy',
		parent: '',
		children: '',
		assets: {
			icon: '',
			dialogImage: '',
			dialogVolatility: '',
			volatility: '',
			button: '',
		},
		text: {
			title: 'BONUS',
			dialog:
				'Buy FREE SPINS for 200× your bet. 3 scatters = 10 FS, 4 = 12 FS, 5 = 15 FS.',
			description: 'Enter FREE SPINS directly (200× bet, 3–5 scatters).',
			button: 'BUY',
			tickerIdle: 'PLACE YOUR BET',
			tickerSpin: 'BONUS BUY',
			bannerText: '',
		},
		maxWin: 25000,
	},
} as const satisfies BetModeMeta;
