import type { GameRuleData } from 'state-shared';

/** Paytable + game rules content for HOME RUN (Strike Zone Gaming). */
export const HOME_RUN_GAME_RULE_META = {
	payTable: [
		{
			title: 'HOME RUN — PAYTABLE',
			rows: 1,
			columns: 1,
			containers: [
				{
					title: 'HOW TO READ',
					text: 'Pays are shown as multiples of your bet. Wins pay left to right on 20 fixed lines. Only the highest win per line is paid.',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
			],
		},
		{
			title: 'HIGH SYMBOLS',
			rows: 2,
			columns: 2,
			containers: [
				{
					title: 'H1 — BATTER',
					text: '5 = 20×\n4 = 10×\n3 = 5×',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
				{
					title: 'H2 — GOLD HELMET',
					text: '5 = 15×\n4 = 5×\n3 = 3×',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 1,
				},
				{
					title: 'H3 — CATCHER',
					text: '5 = 10×\n4 = 3×\n3 = 2×',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 0,
				},
				{
					title: 'H4 — BAT & GLOVE',
					text: '5 = 8×\n4 = 2×\n3 = 1×',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 1,
				},
			],
		},
		{
			title: 'LOW SYMBOLS',
			rows: 2,
			columns: 3,
			containers: [
				{
					title: 'L1 — JERSEY',
					text: '5 = 5×\n4 = 1×\n3 = 0.5×',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
				{
					title: 'L2 — GLOVE',
					text: '5 = 3×\n4 = 0.7×\n3 = 0.3×',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 1,
				},
				{
					title: 'L3 — BASEBALL',
					text: '5 = 3×\n4 = 0.7×\n3 = 0.3×',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 2,
				},
				{
					title: 'L4 — GOLD BAT',
					text: '5 = 2×\n4 = 0.5×\n3 = 0.2×',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 0,
				},
				{
					title: 'L5 — HELMET B',
					text: '5 = 1×\n4 = 0.3×\n3 = 0.1×',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 1,
				},
			],
		},
		{
			title: 'SPECIAL SYMBOLS',
			rows: 2,
			columns: 1,
			containers: [
				{
					title: 'WILD — MULTIPLIER BALL',
					text: 'Substitutes for all symbols except Scatter. Each Wild ball carries a multiplier (×2, ×4, ×5, ×7, ×10…). Several Wilds on the same winning line multiply together (e.g. ×2 × ×3 = ×6). Wild pays: 5 = 20× · 4 = 10× · 3 = 5×.',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
				{
					title: 'SCATTER',
					text: '3 Scatters = 10 Free Spins · 4 = 12 Free Spins · 5 = 15 Free Spins. Scatter does not need to be on a payline.',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 0,
				},
			],
		},
	] satisfies GameRuleData[],
	gameRules: [
		{
			title: 'GAME OVERVIEW',
			rows: 3,
			columns: 1,
			containers: [
				{
					title: 'HOME RUN',
					text: '5 reels × 3 rows · 20 fixed paylines · RTP 96% · Max win ×25 000.',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
				{
					title: 'FREE SPINS',
					text: 'Land 3+ Scatters to trigger Free Spins. 3 → 10 FS · 4 → 12 FS · 5 → 15 FS. During Free Spins, additional Scatters award more spins (2 → +3 · 3 → +5 · 4 → +8 · 5 → +12).',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 0,
				},
				{
					title: 'WILD MULTIPLIERS',
					text: 'Wild baseballs land with multipliers. On a winning line they multiply the line payout. Multiple Wilds on the same line stack as a product.',
					image: '',
					imagePosition: 'left' as const,
					row: 2,
					column: 0,
				},
			],
		},
		{
			title: 'BUY FEATURES',
			rows: 4,
			columns: 1,
			containers: [
				{
					title: 'DOUBLE CHANCE',
					text: '1.25× bet — roughly doubles the chance to trigger Free Spins. Stays on until you turn it off.',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
				{
					title: 'BONUS 3',
					text: '100× bet — force 3 Scatters and enter Free Spins with 10 FS.',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 0,
				},
				{
					title: 'BONUS 4',
					text: '160× bet — force 4 Scatters and enter Free Spins with 12 FS.',
					image: '',
					imagePosition: 'left' as const,
					row: 2,
					column: 0,
				},
				{
					title: 'BONUS',
					text: '200× bet — buy Free Spins with 3–5 Scatters (10 / 12 / 15 FS).',
					image: '',
					imagePosition: 'left' as const,
					row: 3,
					column: 0,
				},
			],
		},
		{
			title: 'CONTROLS',
			rows: 5,
			columns: 1,
			containers: [
				{
					title: 'SPIN',
					text: 'Press Spin (or Space) to play one round at the current bet.',
					image: '',
					imagePosition: 'left' as const,
					row: 0,
					column: 0,
				},
				{
					title: 'BET + / −',
					text: 'Increase or decrease your stake.',
					image: '',
					imagePosition: 'left' as const,
					row: 1,
					column: 0,
				},
				{
					title: 'BUY BONUS',
					text: 'Open the feature buy menu (Double Chance, Bonus 3 / 4, Bonus).',
					image: '',
					imagePosition: 'left' as const,
					row: 2,
					column: 0,
				},
				{
					title: 'TURBO / AUTO',
					text: 'Turbo speeds up spins. Auto Spin plays consecutive rounds.',
					image: '',
					imagePosition: 'left' as const,
					row: 3,
					column: 0,
				},
				{
					title: 'SOUND / SETTINGS',
					text: 'Mute audio or open volume settings (master, music, SFX).',
					image: '',
					imagePosition: 'left' as const,
					row: 4,
					column: 0,
				},
			],
		},
	] satisfies GameRuleData[],
	splashScreen: [] as GameRuleData[],
};
